version: '3.1'

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    network_mode: "bridge"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: collab_dev

networks:
  default:
    driver: bridge
